### ISSUE TITLE
"Link Actor Data" and "Token Disposition" resetting seemingly at random

### ISSUE THREAD

**Issue by oheilo** [vttred/ose#354] opened 2023-02-13 12:33 UTC
### What happened?

The "Link Actor Data" checkbox unchecks and "Token Disposition" resets to hostile on restart of Forge. Sometimes some of the Prototype tokens have settings saved from last session, but usually not.

### What is the expected behaviour?

I would expect settings on prototype tokens not to change without me being responsible.

### Additional Support Details

Foundry Virtual Tabletop v 10
Build 284
Old School Essentials 1.7.5
Active Modules 25

### Foundry VTT Core Version

V10

### Old-School Essentials Core Version

1.7.5

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment] 2023-02-14 21:42
I'm going to ask around the Foundry community, because this sounds like the kind of thing that either a module, Forge, or base Foundry is doing because we're not really touching these properties in any way that should change your experience

**Comment by anthonyronda** [comment] 2023-02-14 21:45
You mention 25 installed modules. To troubleshoot this issue, I recommend uninstalling them all to see if the behavior continues

**Comment by oheilo** [comment] 2023-03-20 16:27
Hi!

Sorry for the late response.
I've tried to deactivate all modules, however the problem persists
It seems that all tokens revert to "hostile" and the "link actor
data"-button becomes unchecked upon refreshing or restarting.

regards

Øyvind Heilo

tir. 14. feb. 2023 kl. 22:45 skrev Anthony Ronda ***@***.***>:

**Comment by anthonyronda** [comment] 2023-03-28 20:36
I think I understand what could be happening:

* You click assign token even without any token selected, but the current active scene has a copy of the prototype token in it: it gets assigned to a token in the scene, not the prototype token
* Some of your tokens are unlinked while your prototype token is linked, or vice versa, meaning you're expecting changes to show on the linked tokens when sometimes they don't. This is allowed! Apparently this is useful to some GMs

If you are able to follow the following steps, I think it's not a bug but it's worth raising as a usability issue with Foundry Gaming

1. Create a new actor, open its character sheet, open its prototype token dialog
2. Select link data checkbox and friendly disposition
3. Click update token
4. Refresh browser page
5. Open the new actor's character sheet and prototype token again. These settings should still be "linked data enabled" and "friendly"

I realize it's happening in a very specific case not reflected here. You will have to show me exact reproduction steps if so. I still don't know any reason why OSE would be doing this, we don't modify tokens at all in the code

**Comment by oheilo** [comment] 2023-03-29 11:46
Hi!
Thanks for replying, even though it seems this is something not OSE related.
I've partly fixed the problem. If I select a token in the Actors menu, set
it to "friendly" and "link actor data" and then put a token to the battle
map, that token seem to remember these states even though i refresh the
window. However, when I refresh the window the prototype token in the
"actors menu" revert back to "hostile" and unchecks "link actor data." So
this creates a new problem as I can never be certain changes to the token
in the "actors menu" applies to the token on the map.

Following the 5 steps above does not work. The character in the actors menu
will not save these states when I refresh. It will save things like
modifying hp's and equipment managing and such. It's just a little weird.

I never had this problem before v10 (been using the program for two years),
but perhaps this is, as you mentioned, an issue I should foreward with the
Foundry team!

Thanks for your pations
regards

øyvind heilo

tir. 28. mar. 2023 kl. 22:36 skrev Anthony Ronda ***@***.***>:

**Comment by anthonyronda** [comment] 2023-04-06 20:47
Hi were you able to resolve this?

**Comment by anthonyronda** [comment] 2023-04-17 13:09
I'm going to close the issue but please feel free to reopen with more details!

**Closed by anthonyronda** 2023-04-17 13:09 UTC
Labels: invalid
