### ISSUE TITLE
No spell/abilities interaction [0.8.9]

### ISSUE THREAD

**Issue by WallaceMcGregor** [vttred/ose#182] opened 2022-05-20 07:44 UTC
When I put an spell on a character the show & roll button does nothing. It doesn't matter If the spell has salvation roll, a regular roll o anything. It doesn't trigger a salvation test on the target or make a dice roll, but It decrease the prepared spell slot. Also, the show button do not show the spell on chat.

Something similar is happening with the abilites. The show and salvation test (this one even isn't clickable) don't work, but the regular roll works fine.

I am in the 0.8.9 and I've tested in Chrome, Edge and the desktop Froundry app.

**Comment by jessev14** [comment] 2022-05-21 21:06
the cause of the issue is here: https://github.com/vttred/ose/blob/d8dbe64a4251eb039a8cc29231d42e64b17de92a/src/module/item/entity.js#L323

need to remove `/dist`

**Comment by WallaceMcGregor** [comment] 2022-05-22 05:59
I've tried this on my local, but It doesn't work.

**Comment by anthonyronda** [comment] 2022-05-23 21:42
Fixed in #183

**Closed by anthonyronda** 2022-05-23 21:42 UTC
