### ISSUE TITLE
Initiative error calculation

### ISSUE THREAD

**Issue by WallaceMcGregor** [vttred/ose#24] opened 2022-01-15 07:03 UTC
With DES 16-17 the initiative bonus -according to the manual- is +1 and with 18 +2. The system applies +2 with 16-17 & +3 with 18. This already happened in U_man's version.

**Comment by anthonyronda** [comment] 2022-01-23 20:36
I can't reproduce this bug. If it's still happening, could you provide your OS and browser?

**Comment by anthonyronda** [comment] 2022-01-23 20:37
Additionally, could you check the Tweaks menu if a +1 was added there?

**Comment by WallaceMcGregor** [comment] 2022-01-24 06:20
It happens in Chrome on a hosted server by a friend (I think it would be some Linux) and on the Foundry desktop app in Windows 10. This is also reported by other members of the Spanish community.

![OSE error iniciativa](https://user-images.githubusercontent.com/17795541/150731855-1ac79a5f-9713-4a18-86e8-7ed8c212428d.jpg)

**Comment by anthonyronda** [comment] 2022-01-26 04:17
Sorry for the delay in finding this one @WallaceMcGregor! It turned out to be a really simple error. The fix will be in Sunday night's release

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/1410433/151103194-634724a3-14cc-43c2-a785-34e8bdecd507.png">

**Comment by WallaceMcGregor** [comment] 2022-01-26 06:16
No problem. You find it, so thats enought 👌🏻

**Closed** 2022-01-28 01:13 UTC
Labels: bug, combat
