### ISSUE TITLE
[IMPORTANT] Attacks from inventory do not work

### ISSUE THREAD

**Issue by NachoTeller** [vttred/ose#121] opened 2022-02-23 19:51 UTC
When you hovered your mouse over the portrait of a weapon, you would see a dice icon to roll. It no longer appears and cannot be rolled from the inventory, making that section of the sheet unusable.

**Comment by anthonyronda** [comment] 2022-02-23 19:55
Duplicate of #115. Fixed in #118. Release will be in about 3 hours.

Instructions to rollback are in #115

**Closed by anthonyronda** 2022-02-23 19:55 UTC
Labels: duplicate
