### ISSUE TITLE
Dropping an item into a container duplicates the item

### ISSUE THREAD

**Issue by eegag** [vttred/ose#209] opened 2022-09-01 18:40 UTC
### What happened?

1. Open character sheet
2. Navigate to inventory tab
3. Dragged GP item into container item
4. GP item duplicated itself in treasure section and did not move to the container

### What is the expected behaviour?

1. Open character sheet
2. Navigate to inventory tab
3. Dragged GP item into container item
4. GP item moves to container section beneath the selected container item and no longer shows in the treasure section

### Additional Support Details

Foundry Virtual Tabletop: Version 10, 10.283
Game System: ose, 1.6.0
Active Modules: 0
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) FoundryVirtualTabletop/10.283.0 Chrome/94.0.4606.81 Electron/15.3.5 Safari/537.36
GPU: ANGLE (NVIDIA, NVIDIA GeForce GTX 760 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671)
Max Texture Size: 16384

Scene: 3840 x 1920 | Grid Size: 100 | Padding Percentage: 0
Walls: 0 | Ambient Lights: 5 | Ambient Sounds: 0 | Tiles: 1 | Tokens: 0

Actors: 1 | Items: 0 | Journal: 0 | Rollable Tables: 0 |
Playlists: 0 | Compendium Packs: 0 | Chat Messages: 1

### Foundry VTT Core Version

V10

### Old-School Essentials Core Version

1.6

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment] 2022-09-01 20:43
There is a change to the dragDrop behavior in V10 that I believe I missed

**Comment by anthonyronda** [comment] 2022-09-01 21:48
Root cause found, appears to be unrelated to the change in the dragDrop API. It's a corner case of the change in the data model

**Comment by anthonyronda** [comment] 2022-09-21 21:42
Fixed in #235

**Closed by anthonyronda** 2022-09-21 21:42 UTC
Labels: bug, inventory-tab
